print("Enter a, b, c, d, e, f: ")
a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
if (a*d-b*c) == 0:
    print("The equation has no solution!")
else:
    x = (e * d - b * f) / (a * d - b * c)
    y = (a * f - e * c) / (a * d - b * c)
    print("x is ", end="")
    print(x, end="")
    print(" and y is ", end="")
    print(y)